create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "nature_score" real not null
);


alter table "public"."categories" enable row level security;

create table "public"."nature_places" (
    "ogc_fid" integer,
    "wkb_geometry" geometry(Point,4326),
    "id" character varying,
    "version" integer,
    "update_time" timestamp with time zone,
    "sources" json,
    "names" json,
    "categories" json,
    "confidence" double precision,
    "websites" character varying[],
    "socials" character varying[],
    "phones" character varying[],
    "brand" json,
    "addresses" json,
    "nature_score" real
);


alter table "public"."nature_places" enable row level security;

CREATE UNIQUE INDEX categories_name_key ON public.categories USING btree (name);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."categories" add constraint "categories_name_key" UNIQUE using index "categories_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.update_nature_places()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    TRUNCATE TABLE nature_places;
    INSERT INTO nature_places
    SELECT p.*, c.nature_score
    FROM places p
    JOIN categories c ON p.categories->>'main' = c.name
    WHERE c.nature_score >= 0.5;
END;
$function$
;

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."nature_places" to "anon";

grant insert on table "public"."nature_places" to "anon";

grant references on table "public"."nature_places" to "anon";

grant select on table "public"."nature_places" to "anon";

grant trigger on table "public"."nature_places" to "anon";

grant truncate on table "public"."nature_places" to "anon";

grant update on table "public"."nature_places" to "anon";

grant delete on table "public"."nature_places" to "authenticated";

grant insert on table "public"."nature_places" to "authenticated";

grant references on table "public"."nature_places" to "authenticated";

grant select on table "public"."nature_places" to "authenticated";

grant trigger on table "public"."nature_places" to "authenticated";

grant truncate on table "public"."nature_places" to "authenticated";

grant update on table "public"."nature_places" to "authenticated";

grant delete on table "public"."nature_places" to "service_role";

grant insert on table "public"."nature_places" to "service_role";

grant references on table "public"."nature_places" to "service_role";

grant select on table "public"."nature_places" to "service_role";

grant trigger on table "public"."nature_places" to "service_role";

grant truncate on table "public"."nature_places" to "service_role";

grant update on table "public"."nature_places" to "service_role";


